#%RAML 0.8
title:

/users/{userId}/achievements:
  get:
    responses:
      200:
        body:
          application/json:
            example: |
              [
                {"id": "99648e19-fcf4-4227-b9e9-99b0fc5e3f2c"}
              ]